import {
  Accessibility,
  Activity,
  Ambulance,
  Armchair,
  Baby,
  BadgeCheck,
  BadgePercent,
  Banknote,
  BedDouble,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Bus,
  CalendarCheck,
  Camera,
  Car,
  ClipboardList,
  Clock,
  Coffee,
  Coins,
  CreditCard,
  Crown,
  Dog,
  Droplet,
  Ear,
  Eye,
  FileText,
  FlaskConical,
  Fuel,
  Gavel,
  Gift,
  Glasses,
  GraduationCap,
  HandCoins,
  HandHeart,
  Handshake,
  HardHat,
  Heart,
  HeartPulse,
  HelpCircle,
  Hospital,
  House,
  IdCard,
  Info,
  Key,
  Landmark,
  Laptop,
  Mail,
  Megaphone,
  MessageCircle,
  Microscope,
  Package,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Printer,
  Receipt,
  Scale,
  Scan,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingCart,
  Smartphone,
  Smile,
  Stamp,
  Star,
  Stethoscope,
  Store,
  Syringe,
  Thermometer,
  Ticket,
  Truck,
  UserRound,
  Users,
  Utensils,
  Wallet,
  Wrench,
  type LucideIcon,
} from 'lucide-react';
import { isImageIcon } from '@gc/shared';
import { assetUrl } from '../lib/api';
import { cx } from './ui';

/** Biblioteca de íconos de servicio, agrupada para el selector. La clave se guarda en el servicio. */
export const SERVICE_ICON_GROUPS: { label: string; icons: Record<string, { icon: LucideIcon; label: string }> }[] = [
  {
    label: 'General',
    icons: {
      ticket: { icon: Ticket, label: 'Ticket' },
      users: { icon: Users, label: 'Personas' },
      user: { icon: UserRound, label: 'Persona' },
      help: { icon: HelpCircle, label: 'Ayuda' },
      info: { icon: Info, label: 'Informes' },
      clipboard: { icon: ClipboardList, label: 'Planilla' },
      file: { icon: FileText, label: 'Documento' },
      calendar: { icon: CalendarCheck, label: 'Agenda' },
      clock: { icon: Clock, label: 'Turno' },
      star: { icon: Star, label: 'Destacado' },
      crown: { icon: Crown, label: 'VIP' },
      accessibility: { icon: Accessibility, label: 'Accesibilidad' },
      armchair: { icon: Armchair, label: 'Sala de espera' },
      megaphone: { icon: Megaphone, label: 'Anuncios' },
      phone: { icon: Phone, label: 'Teléfono' },
      mail: { icon: Mail, label: 'Correo' },
      chat: { icon: MessageCircle, label: 'Consultas' },
      building: { icon: Building2, label: 'Edificio' },
    },
  },
  {
    label: 'Pagos y trámites',
    icons: {
      cash: { icon: Banknote, label: 'Efectivo' },
      card: { icon: CreditCard, label: 'Tarjeta' },
      wallet: { icon: Wallet, label: 'Billetera' },
      bank: { icon: Landmark, label: 'Banco' },
      coins: { icon: Coins, label: 'Monedas' },
      savings: { icon: PiggyBank, label: 'Ahorro' },
      loan: { icon: HandCoins, label: 'Préstamos' },
      receipt: { icon: Receipt, label: 'Recibo' },
      discount: { icon: BadgePercent, label: 'Descuentos' },
      id: { icon: IdCard, label: 'Identidad' },
      stamp: { icon: Stamp, label: 'Sellos' },
      legal: { icon: Scale, label: 'Legal' },
      court: { icon: Gavel, label: 'Juzgado' },
      verified: { icon: BadgeCheck, label: 'Verificación' },
      shield: { icon: ShieldCheck, label: 'Seguro' },
      briefcase: { icon: Briefcase, label: 'Maletín' },
      deal: { icon: Handshake, label: 'Acuerdos' },
    },
  },
  {
    label: 'Salud',
    icons: {
      health: { icon: HeartPulse, label: 'Salud' },
      doctor: { icon: Stethoscope, label: 'Médico' },
      hospital: { icon: Hospital, label: 'Hospital' },
      emergency: { icon: Ambulance, label: 'Urgencias' },
      pharmacy: { icon: Pill, label: 'Farmacia' },
      vaccine: { icon: Syringe, label: 'Vacunas' },
      lab: { icon: FlaskConical, label: 'Laboratorio' },
      microscope: { icon: Microscope, label: 'Análisis' },
      imaging: { icon: Scan, label: 'Imágenes' },
      cardio: { icon: Activity, label: 'Cardiología' },
      heart: { icon: Heart, label: 'Corazón' },
      blood: { icon: Droplet, label: 'Extracción' },
      temperature: { icon: Thermometer, label: 'Triaje' },
      eye: { icon: Eye, label: 'Oftalmología' },
      optics: { icon: Glasses, label: 'Óptica' },
      ear: { icon: Ear, label: 'Audiología' },
      dental: { icon: Smile, label: 'Odontología' },
      mind: { icon: Brain, label: 'Salud mental' },
      baby: { icon: Baby, label: 'Pediatría' },
      bed: { icon: BedDouble, label: 'Internación' },
      care: { icon: HandHeart, label: 'Asistencia social' },
      vet: { icon: Dog, label: 'Veterinaria' },
    },
  },
  {
    label: 'Comercio y servicios',
    icons: {
      cart: { icon: ShoppingCart, label: 'Compras' },
      store: { icon: Store, label: 'Tienda' },
      package: { icon: Package, label: 'Paquete' },
      truck: { icon: Truck, label: 'Envíos' },
      gift: { icon: Gift, label: 'Regalos' },
      tools: { icon: Wrench, label: 'Servicio técnico' },
      phone_repair: { icon: Smartphone, label: 'Celulares' },
      laptop: { icon: Laptop, label: 'Computación' },
      printer: { icon: Printer, label: 'Impresiones' },
      photo: { icon: Camera, label: 'Fotos' },
      clothes: { icon: Shirt, label: 'Ropa' },
      hair: { icon: Scissors, label: 'Peluquería' },
      food: { icon: Utensils, label: 'Comidas' },
      coffee: { icon: Coffee, label: 'Cafetería' },
      car: { icon: Car, label: 'Vehículos' },
      fuel: { icon: Fuel, label: 'Combustible' },
      bus: { icon: Bus, label: 'Transporte' },
      travel: { icon: Plane, label: 'Viajes' },
      home: { icon: House, label: 'Vivienda' },
      key: { icon: Key, label: 'Llaves' },
      works: { icon: HardHat, label: 'Obras' },
      school: { icon: GraduationCap, label: 'Educación' },
      library: { icon: BookOpen, label: 'Biblioteca' },
    },
  },
];

export const SERVICE_ICONS: Record<string, LucideIcon> = Object.fromEntries(
  SERVICE_ICON_GROUPS.flatMap((g) => Object.entries(g.icons).map(([key, v]) => [key, v.icon])),
);

export const SERVICE_ICON_LABELS: Record<string, string> = Object.fromEntries(
  SERVICE_ICON_GROUPS.flatMap((g) => Object.entries(g.icons).map(([key, v]) => [key, v.label])),
);

/** Ícono de un servicio: uno de la biblioteca o una imagen propia subida por la organización. */
export function ServiceIcon({ name, className }: { name: string; className?: string }) {
  if (isImageIcon(name)) return <img src={assetUrl(name)} alt="" className={cx('object-contain', className)} />;
  const Icon = SERVICE_ICONS[name] ?? Ticket;
  return <Icon className={className} />;
}
