import {
  Award,
  BarChart3,
  Bell,
  Building2,
  CalendarCheck,
  Clock,
  Cloud,
  CreditCard,
  Gauge,
  Globe,
  Headset,
  Heart,
  Layers,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  MonitorPlay,
  Palette,
  Phone,
  Printer,
  QrCode,
  Receipt,
  Rocket,
  Settings,
  ShieldCheck,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Tablet,
  Target,
  ThumbsUp,
  Ticket,
  TrendingUp,
  Users,
  Video,
  Volume2,
  Webhook,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { LandingIcon } from '@gc/shared';

export const LANDING_ICON_COMPONENTS: Record<LandingIcon, LucideIcon> = {
  'monitor-play': MonitorPlay,
  video: Video,
  tablet: Tablet,
  smartphone: Smartphone,
  headset: Headset,
  'bar-chart': BarChart3,
  palette: Palette,
  webhook: Webhook,
  building: Building2,
  calendar: CalendarCheck,
  message: MessageCircle,
  bell: Bell,
  shield: ShieldCheck,
  zap: Zap,
  clock: Clock,
  users: Users,
  'credit-card': CreditCard,
  receipt: Receipt,
  globe: Globe,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  ticket: Ticket,
  'qr-code': QrCode,
  printer: Printer,
  volume: Volume2,
  cloud: Cloud,
  lock: Lock,
  rocket: Rocket,
  target: Target,
  'thumbs-up': ThumbsUp,
  layers: Layers,
  settings: Settings,
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  award: Award,
  'trending-up': TrendingUp,
  gauge: Gauge,
  smile: Smile,
};

/** Nombre en español de cada ícono (para el selector). */
export const LANDING_ICON_LABELS: Record<LandingIcon, string> = {
  'monitor-play': 'Pantalla',
  video: 'Video',
  tablet: 'Tablet',
  smartphone: 'Celular',
  headset: 'Atención',
  'bar-chart': 'Gráfico',
  palette: 'Paleta',
  webhook: 'Integración',
  building: 'Edificio',
  calendar: 'Calendario',
  message: 'Mensaje',
  bell: 'Aviso',
  shield: 'Seguridad',
  zap: 'Rapidez',
  clock: 'Reloj',
  users: 'Personas',
  'credit-card': 'Tarjeta',
  receipt: 'Factura',
  globe: 'Mundo',
  sparkles: 'Destellos',
  star: 'Estrella',
  heart: 'Corazón',
  ticket: 'Turno',
  'qr-code': 'Código QR',
  printer: 'Impresora',
  volume: 'Sonido',
  cloud: 'Nube',
  lock: 'Candado',
  rocket: 'Cohete',
  target: 'Objetivo',
  'thumbs-up': 'Me gusta',
  layers: 'Capas',
  settings: 'Ajustes',
  mail: 'Correo',
  phone: 'Teléfono',
  'map-pin': 'Ubicación',
  award: 'Premio',
  'trending-up': 'Crecimiento',
  gauge: 'Velocímetro',
  smile: 'Sonrisa',
};
